ValueError                                Traceback (most recent call last)
File ~\anaconda3\envs\spacyenv\lib\site-packages\spacy\ml\staticvectors.py:58, in forward(model, docs, is_train)
     57 try:
---> 58     vectors_data = model.ops.gemm(V, W, trans2=True)
     59 except ValueError:

File ~\anaconda3\envs\spacyenv\lib\site-packages\thinc\backends\numpy_ops.pyx:93, in thinc.backends.numpy_ops.NumpyOps.gemm()

File ~\anaconda3\envs\spacyenv\lib\site-packages\blis\py.pyx:74, in blis.py.gemm()

ValueError: Shape mismatch for blis.gemm: (65, 0), (300, 96)

During handling of the above exception, another exception occurred:

RuntimeError                              Traceback (most recent call last)
c:\Users\nicol\OneDrive\Desktop\python_stuff\ner_proj\models\test.ipynb Cell 4' in <cell line: 1>()
----> 1 doc = nlp(lengthen_abbreviations("The event is currently being held at National University of Singapore. Like other universities, National University of Singapore will be offering more courses related to sustainability from next year onwards. The College of Humanities and Sciences, located near Clementi Road and Kent Ridge Terminal, for instance, will offer a new second major-only major in Sustainable Urban Development"))
      3 #I stay at Blk 401 CCK Ave 3. My route to URA involves taking bus 975 to CCK Stn, then taking the NSL to JE. At JE I change to the PSR-bound train & taking the EWL to TGP. URA is located at 45 Maxwell Road. To reach it from Tanjong Pagar, exit via Exit A and walk along Peck Seah Street towards Maxwell Road.
      4 displacy.render(doc, style="ent")

File ~\anaconda3\envs\spacyenv\lib\site-packages\spacy\language.py:1022, in Language.__call__(self, text, disable, component_cfg)
   1020     raise ValueError(Errors.E109.format(name=name)) from e
   1021 except Exception as e:
-> 1022     error_handler(name, proc, [doc], e)
   1023 if doc is None:
   1024     raise ValueError(Errors.E005.format(name=name))

File ~\anaconda3\envs\spacyenv\lib\site-packages\spacy\util.py:1617, in raise_error(proc_name, proc, docs, e)
   1616 def raise_error(proc_name, proc, docs, e):
-> 1617     raise e

File ~\anaconda3\envs\spacyenv\lib\site-packages\spacy\language.py:1017, in Language.__call__(self, text, disable, component_cfg)
   1015     error_handler = proc.get_error_handler()
   1016 try:
-> 1017     doc = proc(doc, **component_cfg.get(name, {}))  # type: ignore[call-arg]
   1018 except KeyError as e:
   1019     # This typically happens if a component is not initialized
   1020     raise ValueError(Errors.E109.format(name=name)) from e

File ~\anaconda3\envs\spacyenv\lib\site-packages\spacy\pipeline\trainable_pipe.pyx:56, in spacy.pipeline.trainable_pipe.TrainablePipe.__call__()

File ~\anaconda3\envs\spacyenv\lib\site-packages\spacy\util.py:1617, in raise_error(proc_name, proc, docs, e)
   1616 def raise_error(proc_name, proc, docs, e):
-> 1617     raise e

File ~\anaconda3\envs\spacyenv\lib\site-packages\spacy\pipeline\trainable_pipe.pyx:52, in spacy.pipeline.trainable_pipe.TrainablePipe.__call__()

File ~\anaconda3\envs\spacyenv\lib\site-packages\spacy\pipeline\tok2vec.py:125, in Tok2Vec.predict(self, docs)
    123     width = self.model.get_dim("nO")
    124     return [self.model.ops.alloc((0, width)) for doc in docs]
--> 125 tokvecs = self.model.predict(docs)
    126 batch_id = Tok2VecListener.get_batch_id(docs)
    127 for listener in self.listeners:

File ~\anaconda3\envs\spacyenv\lib\site-packages\thinc\model.py:315, in Model.predict(self, X)
    311 def predict(self, X: InT) -> OutT:
    312     """Call the model's `forward` function with `is_train=False`, and return
    313     only the output, instead of the `(output, callback)` tuple.
    314     """
--> 315     return self._func(self, X, is_train=False)[0]

File ~\anaconda3\envs\spacyenv\lib\site-packages\thinc\layers\chain.py:54, in forward(model, X, is_train)
     52 callbacks = []
     53 for layer in model.layers:
---> 54     Y, inc_layer_grad = layer(X, is_train=is_train)
     55     callbacks.append(inc_layer_grad)
     56     X = Y

File ~\anaconda3\envs\spacyenv\lib\site-packages\thinc\model.py:291, in Model.__call__(self, X, is_train)
    288 def __call__(self, X: InT, is_train: bool) -> Tuple[OutT, Callable]:
    289     """Call the model's `forward` function, returning the output and a
    290     callback to compute the gradients via backpropagation."""
--> 291     return self._func(self, X, is_train=is_train)

File ~\anaconda3\envs\spacyenv\lib\site-packages\thinc\layers\chain.py:54, in forward(model, X, is_train)
     52 callbacks = []
     53 for layer in model.layers:
---> 54     Y, inc_layer_grad = layer(X, is_train=is_train)
     55     callbacks.append(inc_layer_grad)
     56     X = Y

File ~\anaconda3\envs\spacyenv\lib\site-packages\thinc\model.py:291, in Model.__call__(self, X, is_train)
    288 def __call__(self, X: InT, is_train: bool) -> Tuple[OutT, Callable]:
    289     """Call the model's `forward` function, returning the output and a
    290     callback to compute the gradients via backpropagation."""
--> 291     return self._func(self, X, is_train=is_train)

File ~\anaconda3\envs\spacyenv\lib\site-packages\thinc\layers\concatenate.py:44, in forward(model, X, is_train)
     43 def forward(model: Model[InT, OutT], X: InT, is_train: bool) -> Tuple[OutT, Callable]:
---> 44     Ys, callbacks = zip(*[layer(X, is_train=is_train) for layer in model.layers])
     45     if isinstance(Ys[0], list):
     46         return _list_forward(model, X, Ys, callbacks, is_train)  # type: ignore

File ~\anaconda3\envs\spacyenv\lib\site-packages\thinc\layers\concatenate.py:44, in <listcomp>(.0)
     43 def forward(model: Model[InT, OutT], X: InT, is_train: bool) -> Tuple[OutT, Callable]:
---> 44     Ys, callbacks = zip(*[layer(X, is_train=is_train) for layer in model.layers])
     45     if isinstance(Ys[0], list):
     46         return _list_forward(model, X, Ys, callbacks, is_train)  # type: ignore

File ~\anaconda3\envs\spacyenv\lib\site-packages\thinc\model.py:291, in Model.__call__(self, X, is_train)
    288 def __call__(self, X: InT, is_train: bool) -> Tuple[OutT, Callable]:
    289     """Call the model's `forward` function, returning the output and a
    290     callback to compute the gradients via backpropagation."""
--> 291     return self._func(self, X, is_train=is_train)

File ~\anaconda3\envs\spacyenv\lib\site-packages\spacy\ml\staticvectors.py:60, in forward(model, docs, is_train)
     58     vectors_data = model.ops.gemm(V, W, trans2=True)
     59 except ValueError:
---> 60     raise RuntimeError(Errors.E896)
     61 if vocab.vectors.mode == Mode.default:
     62     # Convert negative indices to 0-vectors
     63     # TODO: more options for UNK tokens
     64     vectors_data[rows < 0] = 0

RuntimeError: [E896] There was an error using the static vectors. Ensure that the vectors of the vocab are properly initialized, or set 'include_static_vectors' to False.